const ACTIVITY_ACTIONS = {
    TASK_CREATED: "TASK_CREATED",
    TASK_ASSIGNED: "TASK_ASSIGNED",
    TASK_STATUS_UPDATED:
        "TASK_STATUS_UPDATED",

    MEMBER_ADDED: "MEMBER_ADDED",
    WORKSPACE_CREATED:
        "WORKSPACE_CREATED",

    TASK_COMMENTED:
        "TASK_COMMENTED",
};

module.exports = {
    ACTIVITY_ACTIONS,
};