const ACTIVITY_ACTIONS = {
    TASK_CREATED: "TASK_CREATED",
    TASK_ASSIGNED: "TASK_ASSIGNED",
    TASK_STATUS_UPDATED:
        "TASK_STATUS_UPDATED",
    TASK_COMMENTED:
        "TASK_COMMENTED",
    TASK_DELETED: "TASK_DELETED",

    MEMBER_ADDED: "MEMBER_ADDED",
    WORKSPACE_CREATED:
        "WORKSPACE_CREATED",
};

module.exports = {
    ACTIVITY_ACTIONS,
};